// Code generated by "stringer -type=Decision -output decision_string.go"; DO NOT EDIT.

package simulation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoDecision-0]
	_ = x[DecisionLongPass-1]
	_ = x[DecisionShortPass-2]
	_ = x[DecisionCross-3]
	_ = x[DecisionDribble-4]
	_ = x[DecisionShoot-5]
}

const _Decision_name = "NoDecisionDecisionLongPassDecisionShortPassDecisionCrossDecisionDribbleDecisionShoot"

var _Decision_index = [...]uint8{0, 10, 26, 43, 56, 71, 84}

func (i Decision) String() string {
	if i < 0 || i >= Decision(len(_Decision_index)-1) {
		return "Decision(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Decision_name[_Decision_index[i]:_Decision_index[i+1]]
}
