// Code generated by "stringer -type=EventType -output event_type_string.go"; DO NOT EDIT.

package simulation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ETNone-0]
	_ = x[ETHalfTimeExtraTimeAnnouncement-1]
	_ = x[ETFullTimeExtraTimeAnnouncement-2]
	_ = x[ETHalfTime-3]
	_ = x[ETFullTime-4]
	_ = x[ETSubstitution-5]
	_ = x[ETPenalty-6]
	_ = x[ETFreeKickOnGoal-7]
	_ = x[ETFreeKickDefensiveHalf-8]
	_ = x[ETFoul-9]
	_ = x[ETAdvantage-10]
	_ = x[ETYellowCard-11]
	_ = x[ETRedCard-12]
	_ = x[ETPass-13]
	_ = x[ETGoalScoringChance-14]
	_ = x[ETInterception-15]
	_ = x[ETDribble-16]
}

const _EventType_name = "ETNoneETHalfTimeExtraTimeAnnouncementETFullTimeExtraTimeAnnouncementETHalfTimeETFullTimeETSubstitutionETPenaltyETFreeKickOnGoalETFreeKickDefensiveHalfETFoulETAdvantageETYellowCardETRedCardETPassETGoalScoringChanceETInterceptionETDribble"

var _EventType_index = [...]uint8{0, 6, 37, 68, 78, 88, 102, 111, 127, 150, 156, 167, 179, 188, 194, 213, 227, 236}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
