// Code generated by "stringer -type=EventType -output event_type_string.go"; DO NOT EDIT.

package simulation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeNone-0]
	_ = x[HalfTimeExtraTimeAnnouncement-1]
	_ = x[FullTimeExtraTimeAnnouncement-2]
	_ = x[HalfTime-3]
	_ = x[FullTime-4]
	_ = x[Substitution-5]
	_ = x[Penalty-6]
	_ = x[FreeKickOnGoal-7]
	_ = x[FreeKickDefensiveHalf-8]
	_ = x[Foul-9]
	_ = x[Advantage-10]
	_ = x[YellowCard-11]
	_ = x[RedCard-12]
	_ = x[Pass-13]
	_ = x[GoalScoringChance-14]
}

const _EventType_name = "EventTypeNoneHalfTimeExtraTimeAnnouncementFullTimeExtraTimeAnnouncementHalfTimeFullTimeSubstitutionPenaltyFreeKickOnGoalFreeKickDefensiveHalfFoulAdvantageYellowCardRedCardPassGoalScoringChance"

var _EventType_index = [...]uint8{0, 13, 42, 71, 79, 87, 99, 106, 120, 141, 145, 154, 164, 171, 175, 192}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
