// Code generated by "stringer -type=EventType -output event_type_string.go"; DO NOT EDIT.

package simulation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HalfTimeExtraTimeAnnouncement-0]
	_ = x[FullTimeExtraTimeAnnouncement-1]
	_ = x[HalfTime-2]
	_ = x[FullTime-3]
	_ = x[Substitution-4]
	_ = x[Penalty-5]
	_ = x[FreeKickOnGoal-6]
	_ = x[FreeKickDefensiveHalf-7]
	_ = x[Foul-8]
	_ = x[Advantage-9]
	_ = x[YellowCard-10]
	_ = x[RedCard-11]
	_ = x[HomeTeamAttacking-12]
	_ = x[AwayTeamAttacking-13]
}

const _EventType_name = "HalfTimeExtraTimeAnnouncementFullTimeExtraTimeAnnouncementHalfTimeFullTimeSubstitutionPenaltyFreeKickOnGoalFreeKickDefensiveHalfFoulAdvantageYellowCardRedCardHomeTeamAttackingAwayTeamAttacking"

var _EventType_index = [...]uint8{0, 29, 58, 66, 74, 86, 93, 107, 128, 132, 141, 151, 158, 175, 192}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
