// Code generated by "stringer -type=Interval -output interval_string.go"; DO NOT EDIT.

package simulation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Second-0]
	_ = x[Minute-1]
	_ = x[Hour-2]
}

const _Interval_name = "SecondMinuteHour"

var _Interval_index = [...]uint8{0, 6, 12, 16}

func (i Interval) String() string {
	if i < 0 || i >= Interval(len(_Interval_index)-1) {
		return "Interval(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Interval_name[_Interval_index[i]:_Interval_index[i+1]]
}
