// Code generated by "stringer -type=PlayerPosition -output player_positions_string.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Goalkeeper-0]
	_ = x[RightBack-1]
	_ = x[RightWingBack-2]
	_ = x[CentreBack-3]
	_ = x[LeftBack-4]
	_ = x[LeftWingBack-5]
	_ = x[LeftMidfielder-6]
	_ = x[LeftWinger-7]
	_ = x[CentralMidfielder-8]
	_ = x[CentralDefensiveMidfielder-9]
	_ = x[CentralAttackingMidfieler-10]
	_ = x[CentreForward-11]
	_ = x[RightMidfielder-12]
	_ = x[RightWinger-13]
	_ = x[Striker-14]
}

const _PlayerPosition_name = "GoalkeeperRightBackRightWingBackCentreBackLeftBackLeftWingBackLeftMidfielderLeftWingerCentralMidfielderCentralDefensiveMidfielderCentralAttackingMidfielerCentreForwardRightMidfielderRightWingerStriker"

var _PlayerPosition_index = [...]uint8{0, 10, 19, 32, 42, 50, 62, 76, 86, 103, 129, 154, 167, 182, 193, 200}

func (i PlayerPosition) String() string {
	if i < 0 || i >= PlayerPosition(len(_PlayerPosition_index)-1) {
		return "PlayerPosition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayerPosition_name[_PlayerPosition_index[i]:_PlayerPosition_index[i+1]]
}
