// Code generated by "stringer -type=PlayerPosition -output player_positions_string.go"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Goalkeeper-0]
	_ = x[RightBack-1]
	_ = x[RightWingBack-2]
	_ = x[LeftCentreBack-3]
	_ = x[RightCentreBack-4]
	_ = x[LeftBack-5]
	_ = x[LeftWingBack-6]
	_ = x[LeftMidfielder-7]
	_ = x[LeftWinger-8]
	_ = x[CentralMidfielder-9]
	_ = x[CentralDefensiveMidfielder-10]
	_ = x[CentralAttackingMidfielder-11]
	_ = x[CentreForward-12]
	_ = x[RightMidfielder-13]
	_ = x[RightWinger-14]
	_ = x[Striker-15]
}

const _PlayerPosition_name = "GoalkeeperRightBackRightWingBackLeftCentreBackRightCentreBackLeftBackLeftWingBackLeftMidfielderLeftWingerCentralMidfielderCentralDefensiveMidfielderCentralAttackingMidfielderCentreForwardRightMidfielderRightWingerStriker"

var _PlayerPosition_index = [...]uint8{0, 10, 19, 32, 46, 61, 69, 81, 95, 105, 122, 148, 174, 187, 202, 213, 220}

func (i PlayerPosition) String() string {
	if i < 0 || i >= PlayerPosition(len(_PlayerPosition_index)-1) {
		return "PlayerPosition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayerPosition_name[_PlayerPosition_index[i]:_PlayerPosition_index[i+1]]
}
